### ISSUE TITLE
Support Azure Blob Storage

### ISSUE THREAD

**Issue by wymangr** [boring-registry/boring-registry#113]
Are there (or any plans to add) any other storage options other then S3 bucket? I only have access to Azure. Is there any way to use this with an Azure file share? Or Azure blob? Thanks!

**Comment by oliviermichaelis** [comment]
Hi @wymangr :)
We currently support AWS S3 (and MinIO), as well as Google Cloud Storage and I'd be happy to see support for any object store (like Azure Blob Storage for example).
However, I don't have experience with Azure nor do I have an account set up to play around with it right now. If you're interested in contributing a PR for Azure blob storage support, we'd be really happy help you to get it reviewed and merged!
I can also provide you some pointers for the implementation.

**Comment by dtu-ruth** [comment]
@wymangr did you get a chance to look into the code?

**Comment by wymangr** [comment]
@dtu-ruth Unfortunately I have not had a chance to look into this yet.

**Comment by oliviermichaelis** [comment]
I'm generally interested in adding support for Azure blob storage. Unfortunately, my free time has been filled with various other more important topics, so I haven't had the time to work on this yet. But I'm sure that this will change once the summer is over :)

**Comment by wymangr** [comment]
@oliviermichaelis let me know if you get to it before me. I currently have access to an account and can help test.

**Comment by oliviermichaelis** [comment]
Closing this, as this feature is available in `v0.14.0`
