### ISSUE TITLE
HTTP 500 rather than 404

### ISSUE THREAD

**Issue by timothyclarke** [boring-registry/boring-registry#137]
When making requests to a module / version not in the registry (file does not exist in the S3 bucket) we receive a http 500 response rather than a http 404

If a version does not exist in the backend please generate a 404 rather than 500

**Comment by nc-ruth** [comment]
The same happens when one is unauthenticated against the registry. (500 instead of 401 Unauthorized)

**Comment by oliviermichaelis** [comment]
Thanks for the bug reports @timothyclarke & @nc-ruth! I've just pushed a commit ([e889956](https://github.com/boring-registry/boring-registry/commit/e889956a75b03bb6168e534ebe942a111665ecb2)) to address the problem :)
