### ISSUE TITLE
helm Chart // allow to add a true/false `extraEnv`

### ISSUE THREAD

**Issue by daniel-ciaglia** [boring-registry/boring-registry#164]
at the moment I can not add an add. environment variable

```
extraEnvs:
  - name: BORING_REGISTRY_NETWORK_MIRROR_PULL_THROUGH
    value: "true"
```

As this is simply translated into a Yaml boolean 😭
`json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`

**Comment by oliviermichaelis** [comment]
Good catch, thanks for reporting the issue! :)
Another intricacy of helm + yaml...
