### ISSUE TITLE
[Feature Request] Serve as proxy for remote storage

### ISSUE THREAD

**Issue by XREvo** [boring-registry/boring-registry#180]
Hi,

I'm wondering if Boring could be used as a proxy for module's and provider's files.

## Target use case

We are facing a network configuration "issue":
- Our CICD runners can communicate with the Boring Registry instance deployed locally
- The Boring Registry can communicate with the S3 storage deployed locally
    - When `terraform init`is called on the runners, Boring Registry send them back the URL to download the providers' zip file
- Our CICD runners cannot communicate with the S3 storage deployed locally
    - Don't ask me why, i'm still trying to figure why

So using a dedicated endpoints, when a dedicated configuration is allowed, which serves as proxy to allow content download would be great for this use case.

## Proposed solution

Right now, when you call the API to download a provider, the response contains URL with Shared Access Signature that allow you to download the files from the remote storage. For exemple, with a S3 storage you get something like this :
```json
{
    "os": "linux",
    "arch": "amd64",
    "filename": "terraform-provider-xyz_0.0.0_linux_amd64.zip",
    "download_url": "https://your-s3-provider.com/your-bucket/providers/your-corporation/xyz/terraform-provider-xyz_0.0.0_linux_amd64.zip?X-Amz-Algorithm=...&X-Amz-Credential=...&X-Amz-Date=...&X-Amz-Expires=300&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=...",
    "shasum": "....",
    "shasums_url": "https://your-s3-provider.com/your-bucket/providers/your-corporation/xyz/terraform-provider-xyz_0.0.0_SHA256SUMS?X-Amz-Algorithm=...&X-Amz-Credential=...&X-Amz-Date=...&X-Amz-Expires=300&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=...",
    "shasums_signature_url": "https://your-s3-provider.com/your-bucket/providers/your-corporation/xyz/terraform-provider-xyz_0.0.0_SHA256SUMS.sig?X-Amz-Algorithm=...&X-Amz-Credential=...&X-Amz-Date=...&X-Amz-Expires=300&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=...",
    "signing_keys": {
        "gpg_public_keys": [
            {
                "key_id": "....",
                "ascii_armor": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\n-----END PGP PUBLIC KEY BLOCK-----"
            }
        ]
    }
}
```

Instead of using URLs pointing to your S3 Storage as in the previous exemple, I'm wondering if we can use Boring as a proxy to the remote storage. This would give a json like this :
```json
{
    "os": "linux",
    "arch": "amd64",
    "filename": "terraform-provider-xyz_0.0.0_linux_amd64.zip",
    "download_url": "https://boring-registry.corp.com/v1/providers/your-corporation/xyz/0.0.0/proxy/terraform-provider-xyz_0.0.0_linux_amd64.zip",
    "shasum": "....",
    "shasums_url": "https://boring-registry.corp.com/v1/providers/your-corporation/xyz/0.0.0/proxy/terraform-provider-xyz_0.0.0_SHA256SUMS",
    "shasums_signature_url": "https://boring-registry.corp.com/v1/providers/your-corporation/xyz/0.0.0/proxy/terraform-provider-xyz_0.0.0_SHA256SUMS.sig",
    "signing_keys": {
        "gpg_public_keys": [
            {
                "key_id": "....",
                "ascii_armor": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\n-----END PGP PUBLIC KEY BLOCK-----"
            }
        ]
    }
}
```

> From:
> `https://your-s3-provider.com/your-bucket/providers/your-corporation/xyz/terraform-provider-xyz_0.0.0_linux_amd64.zip`
> To:
> `https://boring-registry.corp.com/v1/providers/your-corporation/xyz/0.0.0/proxy/terraform-provider-xyz_0.0.0_linux_amd64.zip`

Since i don't think that this use case is the primary one, we could activate those endpoints via a flag on the app :
```go
rootCmd.PersistentFlags().BoolVar(&flagProxy, "proxy", false, "Enable proxying download request to remote storage")
```

## Inconvenients

This would add an endpoint that is not referenced by the official Terraform API format

## Conclusion

I think that could be intersting for others users of Boring Registry and i'm ready to take the time needed to code it.  
Tell me what you're thinking of it.

**Comment by XREvo** [comment]
Ping @oliviermichaelis 
Do you have time to read my feature request and discuss about this? (`no` is good answer 😄 it's an OSS project and i know that we all have personal lives that consume most of our free time)

**Comment by XREvo** [comment]
Thanks for yout time!

## My initial thoughs

At first I was thinking of simply returning the `download_url` as a parameter to a generic proxy endpoint, like `https://my-boring.internal.network/v1/proxy/module?download_url=https%3A%2F%2Fs3-instance%2Fproviders%2Fnamespace.something.zip%26Signature%3DABCDEF`
So when the request came back to the server, we just would have to make an HTTP request to the `download_url` endpoint, and send back the response to our request's caller.

And then my memory bringed me back an old discussion with cybersecurity team, that nothing would prevent me from doing a request like `https://my-boring.internal.network/v1/proxy/module?download_url=https%3A%2F%2Fwww.google.com%2F`. I know that `www.google.com` isn't that scary, but it could be an open door for cyber attack (the proxy could be used as a downloading vector, or even could be used to leak data outside of the corporation).

So 2 options were available to me:
1. Control the incoming `download_url`, by asserting that the signature is correct and the target host & bucket are the one known by the instance
2. Using an endpoint similar to the download one, for each need (module, provider, mirror)

Using the dedicated endpoint was a better choice in my opinion when i wrote this issue. Because it was limiting the caller to download only module's or provider's files. And as we would control the files' location, targeting something that doesn't exists is not an option anymore.

## What your answer made me realize

But you made the point about the security. If the second option limits the exposition's surface, it do not answer to "how to be sure that the download is legit?". We still need a way to ensure that the download has been granted. And an obvious solution is to use our own signature method (which isn't that hard in fact, it's just a HMAC encryption).

But before going that way, i started to think back to the 1st option, the generic endpoint, aka `https://my-boring.internal.network/v1/proxy/(module|providers|mirror)`. We would have to control :
- that `download_url` is targeting the configured remote storage,
- that signature is valid, by regenerating it from the `download_url` and then checking if there is a match between the received signature and the computed signature.
To be honest, I'm not sure that the signature matching is feasable because I've never tried to do so (and it would have to be done on 3 different storage providers).  
And if it is not feasable, we will still need an internal mechanism of URL signature.

All of this lead me to the conclusion that implementing a HMAC encryption mechanism managed by the server is the best option for this scenari:
- it's independent from storage drivers (1 implementation versus 3)
- it can be applied on every proxy URLs
- it's stateless

## How i see it working

### When download is granted

We generate the "raw" URL : https://boring-registry.corp.com/v1/providers/your-corporation/xyz/0.0.0/proxy/terraform-provider-xyz_0.0.0_linux_amd64.zip

Then we add 2 query parameters to the URL :
    - The expiracy date
    - A random string

We compute the signature with :
1. The "raw" URL
2. The expiracy date
3. The random string
(in this exact order, and only with values for 2 and 3, not labels)

We add the base64 signature as query parameters to the URL

### When proxy is called

We parse the request URL to get each part.

If expiracy date is older than now, we just don't go further.

Then we compute the signature with :
1. The "raw" URL
2. The expiracy date
3. The random string
(in this exact order, and only with values for 2 and 3, not labels)

If signature don't match, we don't go further.

Otherwise, we use the storage driver to download the file from the proxy URL, and we sned it back to the request caller.

### What about HMAC key?

Well, if proxy is enabled, we have to ask for a key to be used for signature. So adding another parameter to the server like :
```go
rootCmd.PersistentFlags().StringVar(&flagProxySignatureKey, "proxy-signature-key", "", "Key used to pre-sign proxy URLs")
```

And allowing proxy, would set this key as a mandatory configuration.

## Conclusion

I know it's a long response, I hope i didn't scare you 😅

And i'm stil thinking about the solution. What do you think of all this?

**Comment by XREvo** [comment]
Hi @oliviermichaelis 

I tried to implement it in the simplest form that i can think of.

And the result differs from what i've told you, cause managing our own URL signature helps to cover most use cases.

So I added a `/v1/proxy` endpoint that require 3 parameters :
1. A signature : To ensure that we allowed this download
2. An expiry : Unix timestamp, aligned with the remote storage expiry
3.The download URL : The original remote storage presigned URL, encoded in base64, so we can just use it as is to proxy the file

Proxy URL looks like: `http://localhost:5601/v1/proxy/3278b6f5c30818b118898ae8450efb5175cadb95222a126ed2541579e6c6a0ec/6569286998/aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbQ`
|Part|Value|
|---|---|
|Signature|3278b6f5c30818b118898ae8450efb5175cadb95222a126ed2541579e6c6a0ec|
|Expiry|6569286998|
|URL|aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbQ|

I've tried to implement it to be as least verbose as i can think of for the module and provider packages :
- They have a dependency on an internal service that manage proxy URL building
- They only use it if proxy is enabled

Let me know what you think of it

**Comment by oliviermichaelis** [comment]
First of all thanks for the long posts! I think it helps to understand your thought process and where you're coming from (and what you've thought about) :)

I have some questions which I will list in the following:

### Can we re-use the existing verification mechanism for pre-signed URLs of the storage backend instead of introducing our own?
The pre-signed URL is already signed with an expiration. I think we can just forward the download request to our storage provider (S3, GCS, Azure blob storage, Minio, ...) and let it figure out whether it's a valid request or not.
To prevent that a client can send any URL and abuse the boring-registry as a network proxy, we should probably replace the part of the domain to something we control. For example the bucket base URL.

For example, for the following pre-signed URL for a provider:
```
https://minio.internal/boring-registry/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=89mEEKCRuo0xshIxqL9j%2F20240604%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240604T214232Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=3d9402ee89158fd57a037da7ffe7d7c6cb0344443fbac50e9256d4906b62c9a2
```

We could reply with the following `download_url`:
 ```
/v1/proxy/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=89mEEKCRuo0xshIxqL9j%2F20240604%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240604T214232Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=3d9402ee89158fd57a037da7ffe7d7c6cb0344443fbac50e9256d4906b62c9a2
 ```
_The host is omitted, the provider registry protocol supports relative paths. But I would have to test it out to see what the client would actually expect. See the documentation [here](https://developer.hashicorp.com/terraform/internals/provider-registry-protocol#download_url)_

When the client sends the request, we can use the part after `/v1/proxy` to reconstruct a valid URL to our storage backend.
For S3, it could for example be something like:
```go
fmt.Sprintf("https://%s.s3.%s.amazonaws.com", bucket, region)
```
And then perform a request to the storage backend and let it deal with the complexity whether it's valid.
We just have to make sure that we can construct the host for every of our storage backends :)

What are your thoughts on that?

**Comment by XREvo** [comment]
Hi!

Sorry for the late response 🙏 

I think that yes, your proposal should work very fine (at least for s3).  
This would really simplify the implementation on the proxy part since no HMAC computation will have to be done.

The only place where it could raise issue would be about other storage provider, like the local file system asked in the issue #135. With this storage provider no presigned-URL would be generated, so :
1. Is it still relevant use case ?
2. I don't know where the PR is right know, can we implement the HMAC mechanism in this storage provider ? 🤷‍♂️ 

I want to give a try to your solution and do a quick implementation of it but I'll be pretty busy in the next days, so I think I won't have the time to look at it until middle of the next week.

I'll let you know when i will find time to check and test it against the 2 other storage providers.

Have a nice day

**Comment by oliviermichaelis** [comment]
Regarding #135, there hasn't been any work on it for almost a year. There are also some other issues that need to be addressed before it would get merged. For example, there is currently no authorization for the download part, so we definitely do not have to consider a solution for our authorization problem that would work with #135.

I checked the format for the following storage providers:

* MinIO `https://minio.internal/boring-registry/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip`
* AWS S3 `boring-registry.s3.amazonaws.com/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip`
* GCS `https://storage.googleapis.com/example-bucket/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip`
* Azure blob storage `https://example.blob.core.windows.net/boring-registry/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip`

I omitted the query params with the presigned/shared access tokens. But I think it should be possible to implement for all storage providers :)


> I'll be pretty busy in the next days, so I think I won't have the time to look at it until middle of the next week.

No stress, I'm also quite busy right now. I will generally try to answer/help as soon as possible, but it could take a couple of days until I find the time to answer

**Comment by XREvo** [comment]
Hi @oliviermichaelis 

I've completed my work on PR https://github.com/boring-registry/boring-registry/issues/180 with the process you've detailed :
- I split the string to remove the scheme and hostname for the download URL
- I URL encode the rest and use it as proxy URL
- Then the URL is decoded when the proxy is called, and a new method on each Storage rebuild the full URL that will be downloaded then

Can you look at the PR?

_**Note :** I've only tested it uppon S3, since I don't have any Azure or GCS account_

**Comment by oliviermichaelis** [comment]
The feature is now release in [v0.15.0](https://github.com/boring-registry/boring-registry/releases/tag/v0.15.0) :tada: 
Thank you for your contribution!
