### ISSUE TITLE
[BUG] Boring-registry upload concatenates file name with extension

### ISSUE THREAD

**Issue by tszebeni-asml** [boring-registry/boring-registry#182]
I noticed when I upload to GCS via boring-registry upload command, the resulted archive file contains:
boring-registryhcl
maintf

Notice the missing dot from filenames.
After fetching the module the filenames are still wrong.

Expectations:
boring-registry.hcl
main.tf

I was executing "boring-registry upload --flags... ." from current folder, once I cd-d back to parent folder I could execute the command with folder name and seems working.

**Comment by oliviermichaelis** [comment]
Hi @tszebeni-asml! Thanks for your bug report. Just to clarify, for the following directory structure:
```
.
└── modules/
    └── example-module/
        ├── main.tf
        └── boring-registry.hcl
```
you performed:
```
$ cd modules/example-module
$ boring-registry upload --flags... .
```
which did not work.

But the following worked?
```
$ cd modules
$ boring-registry upload --flags... ./example-module
```

I will try to reproduce it when I have some free time :)

**Comment by tszebeni-asml** [comment]
Hi @oliviermichaelis ,
Yes I did as you mention.
