### ISSUE TITLE
[Feature]: Enhance the way proxy URL are managed

### ISSUE THREAD

**Issue by XREvo** [boring-registry/boring-registry#192]
Currently the root part of the URL coming from the proxy (aka `scheme://host`) is retreived from the incoming HTTP request.

This implementation was naive (my bad ! I'm the author).  
And it can (must?) be enhanced for use case where:
- you are behind a proxy that manage public facing URL for you.  
Terraform CLI call https://boring.corp.tld, which is a load balancer that call http://boring.internal.corp.tld (no TLS behind Load Balancer). In this case, the proxy URL will redirect download to http://boring.internal.corp.tld which may be invalid.
- you want to use a custom URL (for whatever reason you have)

Therefore i think that we can do 2 more things :
- add an CLI argument that allow to define the root URL of proxy URLs
- add steps to read http request X-FORWARDED-* headers, and use them to build the root URL of proxy URLs

If the CLI argument is set, it'll be used by default, no matter the X-FORWARDED-* headers.  
Else, if X-FORWARDED-* headers are set, they will be used.  
Otherwise, we use the current way of building the root URL.

**Comment by XREvo** [comment]
And by the way, i'm in the case of `for whatever reason you have`  
The X-FORWARDED-* headers sent by our LoadBalancer are invalid...

**Comment by oliviermichaelis** [comment]
Hi @XREvo :wave: 

Thanks for the bug report and providing a solution to the problem! 
I think there is potentially another solution to the problem which could also simplify the existing URL handling for the download proxy.
The [Provider Registry Protocol](https://developer.hashicorp.com/terraform/internals/provider-registry-protocol#download_url) and the [Module Registry Protocol ](https://developer.hashicorp.com/terraform/internals/module-registry-protocol#sample-response-1) support responding with a relative download URL.

Documentation for the `download_url` of a provider:
> [download_url](https://developer.hashicorp.com/terraform/internals/provider-registry-protocol#download_url) (required): a URL from which Terraform can retrieve the provider's zip archive. If this is a relative URL then it will be resolved relative to the URL that returned the containing JSON object.

Documentation for the module download response:
> The value of X-Terraform-Get may instead be a relative URL, indicated by beginning with /, ./ or ../, in which case it is resolved relative to the full URL of the download endpoint to produce [an HTTP URL module source](https://developer.hashicorp.com/terraform/language/modules/sources#http-urls).

If we respond with a relative URL, we should fix the problems you described, right?

**Comment by XREvo** [comment]
Yes, i guess so

I'll implement it and try it next monday at work. If it works, i'll update my PR in that way

**Comment by oliviermichaelis** [comment]
Thanks, let me know if you need any feedback or help otherwise :)

**Comment by XREvo** [comment]
Hi @oliviermichaelis

I've coded it and tested it locally.  
Without suprise, it works perfectly and simplifies the code 🥳 

My PR is up to date

**Comment by oliviermichaelis** [comment]
That was quick!
I wish we had found the solution sooner and that you could have saved yourself some implementation effort.

**Comment by XREvo** [comment]
Indeed, the sooner will be the better, but if you have some things pending and need time to complete them, i'll wait.

**Comment by XREvo** [comment]
And thanks for your feedback. It simplifies **a lot** the source code 😄

**Comment by XREvo** [comment]
😱

I tested it with a local terraform project but didn't rerun the test

I'm sorry @oliviermichaelis i'll fix that this afternoon

**Comment by oliviermichaelis** [comment]
This should be fixed in [0.15.2](https://github.com/boring-registry/boring-registry/releases/tag/v0.15.2)
